package main

import (
	"github.com/app-store-connect-api/mcp-server/config"
	"github.com/app-store-connect-api/mcp-server/models"
	tools_apppricepoints "github.com/app-store-connect-api/mcp-server/tools/apppricepoints"
	tools_appencryptiondeclarations "github.com/app-store-connect-api/mcp-server/tools/appencryptiondeclarations"
	tools_builds "github.com/app-store-connect-api/mcp-server/tools/builds"
	tools_apps "github.com/app-store-connect-api/mcp-server/tools/apps"
	tools_bundleidcapabilities "github.com/app-store-connect-api/mcp-server/tools/bundleidcapabilities"
	tools_betaapplocalizations "github.com/app-store-connect-api/mcp-server/tools/betaapplocalizations"
	tools_profiles "github.com/app-store-connect-api/mcp-server/tools/profiles"
	tools_appscreenshotsets "github.com/app-store-connect-api/mcp-server/tools/appscreenshotsets"
	tools_devices "github.com/app-store-connect-api/mcp-server/tools/devices"
	tools_appstoreversions "github.com/app-store-connect-api/mcp-server/tools/appstoreversions"
	tools_betaappreviewsubmissions "github.com/app-store-connect-api/mcp-server/tools/betaappreviewsubmissions"
	tools_betalicenseagreements "github.com/app-store-connect-api/mcp-server/tools/betalicenseagreements"
	tools_routingappcoverages "github.com/app-store-connect-api/mcp-server/tools/routingappcoverages"
	tools_users "github.com/app-store-connect-api/mcp-server/tools/users"
	tools_userinvitations "github.com/app-store-connect-api/mcp-server/tools/userinvitations"
	tools_bundleids "github.com/app-store-connect-api/mcp-server/tools/bundleids"
	tools_betagroups "github.com/app-store-connect-api/mcp-server/tools/betagroups"
	tools_appscreenshots "github.com/app-store-connect-api/mcp-server/tools/appscreenshots"
	tools_enduserlicenseagreements "github.com/app-store-connect-api/mcp-server/tools/enduserlicenseagreements"
	tools_appstorereviewattachments "github.com/app-store-connect-api/mcp-server/tools/appstorereviewattachments"
	tools_appcategories "github.com/app-store-connect-api/mcp-server/tools/appcategories"
	tools_betaappreviewdetails "github.com/app-store-connect-api/mcp-server/tools/betaappreviewdetails"
	tools_prereleaseversions "github.com/app-store-connect-api/mcp-server/tools/prereleaseversions"
	tools_buildbetanotifications "github.com/app-store-connect-api/mcp-server/tools/buildbetanotifications"
	tools_appstoreversionsubmissions "github.com/app-store-connect-api/mcp-server/tools/appstoreversionsubmissions"
	tools_gamecenterenabledversions "github.com/app-store-connect-api/mcp-server/tools/gamecenterenabledversions"
	tools_appstoreversionlocalizations "github.com/app-store-connect-api/mcp-server/tools/appstoreversionlocalizations"
	tools_buildbetadetails "github.com/app-store-connect-api/mcp-server/tools/buildbetadetails"
	tools_ageratingdeclarations "github.com/app-store-connect-api/mcp-server/tools/ageratingdeclarations"
	tools_appprices "github.com/app-store-connect-api/mcp-server/tools/appprices"
	tools_apppreviews "github.com/app-store-connect-api/mcp-server/tools/apppreviews"
	tools_apppreviewsets "github.com/app-store-connect-api/mcp-server/tools/apppreviewsets"
	tools_betatesters "github.com/app-store-connect-api/mcp-server/tools/betatesters"
	tools_betabuildlocalizations "github.com/app-store-connect-api/mcp-server/tools/betabuildlocalizations"
	tools_inapppurchases "github.com/app-store-connect-api/mcp-server/tools/inapppurchases"
	tools_appstorereviewdetails "github.com/app-store-connect-api/mcp-server/tools/appstorereviewdetails"
	tools_certificates "github.com/app-store-connect-api/mcp-server/tools/certificates"
	tools_apppricetiers "github.com/app-store-connect-api/mcp-server/tools/apppricetiers"
	tools_appinfolocalizations "github.com/app-store-connect-api/mcp-server/tools/appinfolocalizations"
	tools_betatesterinvitations "github.com/app-store-connect-api/mcp-server/tools/betatesterinvitations"
	tools_appinfos "github.com/app-store-connect-api/mcp-server/tools/appinfos"
	tools_appstoreversionphasedreleases "github.com/app-store-connect-api/mcp-server/tools/appstoreversionphasedreleases"
	tools_diagnosticsignatures "github.com/app-store-connect-api/mcp-server/tools/diagnosticsignatures"
	tools_territories "github.com/app-store-connect-api/mcp-server/tools/territories"
	tools_idfadeclarations "github.com/app-store-connect-api/mcp-server/tools/idfadeclarations"
	tools_apppreorders "github.com/app-store-connect-api/mcp-server/tools/apppreorders"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_apppricepoints.CreateApppricepoints_territory_get_to_one_relatedTool(cfg),
		tools_appencryptiondeclarations.CreateAppencryptiondeclarations_app_get_to_one_relatedTool(cfg),
		tools_builds.CreateBuilds_app_get_to_one_relatedTool(cfg),
		tools_apps.CreateApps_preorder_get_to_one_relatedTool(cfg),
		tools_appencryptiondeclarations.CreateAppencryptiondeclarations_builds_create_to_many_relationshipTool(cfg),
		tools_bundleidcapabilities.CreateBundleidcapabilities_create_instanceTool(cfg),
		tools_builds.CreateBuilds_betaappreviewsubmission_get_to_one_relatedTool(cfg),
		tools_betaapplocalizations.CreateBetaapplocalizations_delete_instanceTool(cfg),
		tools_betaapplocalizations.CreateBetaapplocalizations_get_instanceTool(cfg),
		tools_betaapplocalizations.CreateBetaapplocalizations_update_instanceTool(cfg),
		tools_profiles.CreateProfiles_bundleid_get_to_one_relatedTool(cfg),
		tools_appscreenshotsets.CreateAppscreenshotsets_appscreenshots_get_to_many_relatedTool(cfg),
		tools_devices.CreateDevices_get_instanceTool(cfg),
		tools_devices.CreateDevices_update_instanceTool(cfg),
		tools_builds.CreateBuilds_betagroups_delete_to_many_relationshipTool(cfg),
		tools_builds.CreateBuilds_betagroups_create_to_many_relationshipTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_appstoreversionphasedrelease_get_to_one_relatedTool(cfg),
		tools_betaappreviewsubmissions.CreateBetaappreviewsubmissions_build_get_to_one_relatedTool(cfg),
		tools_betalicenseagreements.CreateBetalicenseagreements_get_collectionTool(cfg),
		tools_routingappcoverages.CreateRoutingappcoverages_delete_instanceTool(cfg),
		tools_routingappcoverages.CreateRoutingappcoverages_get_instanceTool(cfg),
		tools_routingappcoverages.CreateRoutingappcoverages_update_instanceTool(cfg),
		tools_users.CreateUsers_get_instanceTool(cfg),
		tools_users.CreateUsers_update_instanceTool(cfg),
		tools_users.CreateUsers_delete_instanceTool(cfg),
		tools_betaapplocalizations.CreateBetaapplocalizations_app_get_to_one_relatedTool(cfg),
		tools_userinvitations.CreateUserinvitations_visibleapps_get_to_many_relatedTool(cfg),
		tools_bundleids.CreateBundleids_bundleidcapabilities_get_to_many_relatedTool(cfg),
		tools_betagroups.CreateBetagroups_builds_delete_to_many_relationshipTool(cfg),
		tools_betagroups.CreateBetagroups_builds_get_to_many_relationshipTool(cfg),
		tools_betagroups.CreateBetagroups_builds_create_to_many_relationshipTool(cfg),
		tools_apps.CreateApps_betalicenseagreement_get_to_one_relatedTool(cfg),
		tools_betagroups.CreateBetagroups_builds_get_to_many_relatedTool(cfg),
		tools_betaappreviewsubmissions.CreateBetaappreviewsubmissions_get_instanceTool(cfg),
		tools_bundleids.CreateBundleids_create_instanceTool(cfg),
		tools_bundleids.CreateBundleids_get_collectionTool(cfg),
		tools_userinvitations.CreateUserinvitations_get_collectionTool(cfg),
		tools_userinvitations.CreateUserinvitations_create_instanceTool(cfg),
		tools_appscreenshots.CreateAppscreenshots_create_instanceTool(cfg),
		tools_apps.CreateApps_prereleaseversions_get_to_many_relatedTool(cfg),
		tools_profiles.CreateProfiles_delete_instanceTool(cfg),
		tools_profiles.CreateProfiles_get_instanceTool(cfg),
		tools_enduserlicenseagreements.CreateEnduserlicenseagreements_territories_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_prereleaseversion_get_to_one_relatedTool(cfg),
		tools_apps.CreateApps_perfpowermetrics_get_to_many_relatedTool(cfg),
		tools_appstorereviewattachments.CreateAppstorereviewattachments_delete_instanceTool(cfg),
		tools_appstorereviewattachments.CreateAppstorereviewattachments_get_instanceTool(cfg),
		tools_appstorereviewattachments.CreateAppstorereviewattachments_update_instanceTool(cfg),
		tools_enduserlicenseagreements.CreateEnduserlicenseagreements_update_instanceTool(cfg),
		tools_enduserlicenseagreements.CreateEnduserlicenseagreements_delete_instanceTool(cfg),
		tools_enduserlicenseagreements.CreateEnduserlicenseagreements_get_instanceTool(cfg),
		tools_appcategories.CreateAppcategories_parent_get_to_one_relatedTool(cfg),
		tools_appcategories.CreateAppcategories_subcategories_get_to_many_relatedTool(cfg),
		tools_betaappreviewdetails.CreateBetaappreviewdetails_get_collectionTool(cfg),
		tools_prereleaseversions.CreatePrereleaseversions_builds_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_perfpowermetrics_get_to_many_relatedTool(cfg),
		tools_betagroups.CreateBetagroups_app_get_to_one_relatedTool(cfg),
		tools_buildbetanotifications.CreateBuildbetanotifications_create_instanceTool(cfg),
		tools_apps.CreateApps_get_collectionTool(cfg),
		tools_users.CreateUsers_visibleapps_get_to_many_relatedTool(cfg),
		tools_appstoreversionsubmissions.CreateAppstoreversionsubmissions_delete_instanceTool(cfg),
		tools_betagroups.CreateBetagroups_get_collectionTool(cfg),
		tools_betagroups.CreateBetagroups_create_instanceTool(cfg),
		tools_betaappreviewdetails.CreateBetaappreviewdetails_app_get_to_one_relatedTool(cfg),
		tools_apps.CreateApps_appstoreversions_get_to_many_relatedTool(cfg),
		tools_gamecenterenabledversions.CreateGamecenterenabledversions_compatibleversions_delete_to_many_relationshipTool(cfg),
		tools_gamecenterenabledversions.CreateGamecenterenabledversions_compatibleversions_get_to_many_relationshipTool(cfg),
		tools_gamecenterenabledversions.CreateGamecenterenabledversions_compatibleversions_replace_to_many_relationshipTool(cfg),
		tools_gamecenterenabledversions.CreateGamecenterenabledversions_compatibleversions_create_to_many_relationshipTool(cfg),
		tools_apppricepoints.CreateApppricepoints_get_collectionTool(cfg),
		tools_appstoreversionlocalizations.CreateAppstoreversionlocalizations_appscreenshotsets_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_betabuildlocalizations_get_to_many_relatedTool(cfg),
		tools_appstoreversionlocalizations.CreateAppstoreversionlocalizations_create_instanceTool(cfg),
		tools_buildbetadetails.CreateBuildbetadetails_build_get_to_one_relatedTool(cfg),
		tools_appscreenshotsets.CreateAppscreenshotsets_appscreenshots_get_to_many_relationshipTool(cfg),
		tools_appscreenshotsets.CreateAppscreenshotsets_appscreenshots_replace_to_many_relationshipTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_create_instanceTool(cfg),
		tools_apps.CreateApps_appinfos_get_to_many_relatedTool(cfg),
		tools_betaapplocalizations.CreateBetaapplocalizations_get_collectionTool(cfg),
		tools_betaapplocalizations.CreateBetaapplocalizations_create_instanceTool(cfg),
		tools_ageratingdeclarations.CreateAgeratingdeclarations_update_instanceTool(cfg),
		tools_appscreenshotsets.CreateAppscreenshotsets_create_instanceTool(cfg),
		tools_apps.CreateApps_betatesters_delete_to_many_relationshipTool(cfg),
		tools_appprices.CreateAppprices_get_instanceTool(cfg),
		tools_apppreviews.CreateApppreviews_delete_instanceTool(cfg),
		tools_apppreviews.CreateApppreviews_get_instanceTool(cfg),
		tools_apppreviews.CreateApppreviews_update_instanceTool(cfg),
		tools_apppreviews.CreateApppreviews_create_instanceTool(cfg),
		tools_apppreviewsets.CreateApppreviewsets_delete_instanceTool(cfg),
		tools_apppreviewsets.CreateApppreviewsets_get_instanceTool(cfg),
		tools_builds.CreateBuilds_diagnosticsignatures_get_to_many_relatedTool(cfg),
		tools_apppricepoints.CreateApppricepoints_get_instanceTool(cfg),
		tools_profiles.CreateProfiles_devices_get_to_many_relatedTool(cfg),
		tools_betagroups.CreateBetagroups_betatesters_delete_to_many_relationshipTool(cfg),
		tools_betagroups.CreateBetagroups_betatesters_get_to_many_relationshipTool(cfg),
		tools_betagroups.CreateBetagroups_betatesters_create_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_betagroups_delete_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_betagroups_get_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_betagroups_create_to_many_relationshipTool(cfg),
		tools_builds.CreateBuilds_icons_get_to_many_relatedTool(cfg),
		tools_userinvitations.CreateUserinvitations_delete_instanceTool(cfg),
		tools_userinvitations.CreateUserinvitations_get_instanceTool(cfg),
		tools_prereleaseversions.CreatePrereleaseversions_get_instanceTool(cfg),
		tools_betabuildlocalizations.CreateBetabuildlocalizations_get_collectionTool(cfg),
		tools_betabuildlocalizations.CreateBetabuildlocalizations_create_instanceTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_ageratingdeclaration_get_to_one_relatedTool(cfg),
		tools_betabuildlocalizations.CreateBetabuildlocalizations_delete_instanceTool(cfg),
		tools_betabuildlocalizations.CreateBetabuildlocalizations_get_instanceTool(cfg),
		tools_betabuildlocalizations.CreateBetabuildlocalizations_update_instanceTool(cfg),
		tools_buildbetadetails.CreateBuildbetadetails_get_instanceTool(cfg),
		tools_buildbetadetails.CreateBuildbetadetails_update_instanceTool(cfg),
		tools_inapppurchases.CreateInapppurchases_get_instanceTool(cfg),
		tools_appstorereviewdetails.CreateAppstorereviewdetails_appstorereviewattachments_get_to_many_relatedTool(cfg),
		tools_bundleidcapabilities.CreateBundleidcapabilities_delete_instanceTool(cfg),
		tools_bundleidcapabilities.CreateBundleidcapabilities_update_instanceTool(cfg),
		tools_certificates.CreateCertificates_get_collectionTool(cfg),
		tools_certificates.CreateCertificates_create_instanceTool(cfg),
		tools_betagroups.CreateBetagroups_delete_instanceTool(cfg),
		tools_betagroups.CreateBetagroups_get_instanceTool(cfg),
		tools_betagroups.CreateBetagroups_update_instanceTool(cfg),
		tools_apps.CreateApps_gamecenterenabledversions_get_to_many_relatedTool(cfg),
		tools_apppricetiers.CreateApppricetiers_pricepoints_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_update_instanceTool(cfg),
		tools_builds.CreateBuilds_get_instanceTool(cfg),
		tools_devices.CreateDevices_get_collectionTool(cfg),
		tools_devices.CreateDevices_create_instanceTool(cfg),
		tools_users.CreateUsers_visibleapps_replace_to_many_relationshipTool(cfg),
		tools_users.CreateUsers_visibleapps_create_to_many_relationshipTool(cfg),
		tools_users.CreateUsers_visibleapps_delete_to_many_relationshipTool(cfg),
		tools_users.CreateUsers_visibleapps_get_to_many_relationshipTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_appstoreversionsubmission_get_to_one_relatedTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_build_update_to_one_relationshipTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_build_get_to_one_relationshipTool(cfg),
		tools_appstoreversionsubmissions.CreateAppstoreversionsubmissions_create_instanceTool(cfg),
		tools_builds.CreateBuilds_get_collectionTool(cfg),
		tools_appscreenshotsets.CreateAppscreenshotsets_delete_instanceTool(cfg),
		tools_appscreenshotsets.CreateAppscreenshotsets_get_instanceTool(cfg),
		tools_appstorereviewdetails.CreateAppstorereviewdetails_get_instanceTool(cfg),
		tools_appstorereviewdetails.CreateAppstorereviewdetails_update_instanceTool(cfg),
		tools_apps.CreateApps_builds_get_to_many_relatedTool(cfg),
		tools_appinfolocalizations.CreateAppinfolocalizations_create_instanceTool(cfg),
		tools_apps.CreateApps_betagroups_get_to_many_relatedTool(cfg),
		tools_apps.CreateApps_prices_get_to_many_relatedTool(cfg),
		tools_betaappreviewsubmissions.CreateBetaappreviewsubmissions_get_collectionTool(cfg),
		tools_betaappreviewsubmissions.CreateBetaappreviewsubmissions_create_instanceTool(cfg),
		tools_betatesterinvitations.CreateBetatesterinvitations_create_instanceTool(cfg),
		tools_prereleaseversions.CreatePrereleaseversions_get_collectionTool(cfg),
		tools_betatesters.CreateBetatesters_apps_delete_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_apps_get_to_many_relationshipTool(cfg),
		tools_appinfos.CreateAppinfos_primarycategory_get_to_one_relatedTool(cfg),
		tools_apppreviewsets.CreateApppreviewsets_apppreviews_get_to_many_relationshipTool(cfg),
		tools_apppreviewsets.CreateApppreviewsets_apppreviews_replace_to_many_relationshipTool(cfg),
		tools_appinfos.CreateAppinfos_secondarysubcategoryone_get_to_one_relatedTool(cfg),
		tools_apppreviewsets.CreateApppreviewsets_apppreviews_get_to_many_relatedTool(cfg),
		tools_buildbetadetails.CreateBuildbetadetails_get_collectionTool(cfg),
		tools_appinfolocalizations.CreateAppinfolocalizations_delete_instanceTool(cfg),
		tools_appinfolocalizations.CreateAppinfolocalizations_get_instanceTool(cfg),
		tools_appinfolocalizations.CreateAppinfolocalizations_update_instanceTool(cfg),
		tools_appencryptiondeclarations.CreateAppencryptiondeclarations_get_collectionTool(cfg),
		tools_gamecenterenabledversions.CreateGamecenterenabledversions_compatibleversions_get_to_many_relatedTool(cfg),
		tools_appinfos.CreateAppinfos_primarysubcategorytwo_get_to_one_relatedTool(cfg),
		tools_appinfos.CreateAppinfos_ageratingdeclaration_get_to_one_relatedTool(cfg),
		tools_bundleids.CreateBundleids_profiles_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_appstoreversion_get_to_one_relatedTool(cfg),
		tools_bundleids.CreateBundleids_get_instanceTool(cfg),
		tools_bundleids.CreateBundleids_update_instanceTool(cfg),
		tools_bundleids.CreateBundleids_delete_instanceTool(cfg),
		tools_appstoreversionlocalizations.CreateAppstoreversionlocalizations_delete_instanceTool(cfg),
		tools_appstoreversionlocalizations.CreateAppstoreversionlocalizations_get_instanceTool(cfg),
		tools_appstoreversionlocalizations.CreateAppstoreversionlocalizations_update_instanceTool(cfg),
		tools_apps.CreateApps_enduserlicenseagreement_get_to_one_relatedTool(cfg),
		tools_apppreviewsets.CreateApppreviewsets_create_instanceTool(cfg),
		tools_prereleaseversions.CreatePrereleaseversions_app_get_to_one_relatedTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_appstorereviewdetail_get_to_one_relatedTool(cfg),
		tools_betatesters.CreateBetatesters_builds_delete_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_builds_get_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_builds_create_to_many_relationshipTool(cfg),
		tools_apps.CreateApps_availableterritories_get_to_many_relatedTool(cfg),
		tools_appstoreversionphasedreleases.CreateAppstoreversionphasedreleases_create_instanceTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_routingappcoverage_get_to_one_relatedTool(cfg),
		tools_users.CreateUsers_get_collectionTool(cfg),
		tools_apppricetiers.CreateApppricetiers_get_collectionTool(cfg),
		tools_diagnosticsignatures.CreateDiagnosticsignatures_logs_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_appencryptiondeclaration_get_to_one_relatedTool(cfg),
		tools_appstorereviewattachments.CreateAppstorereviewattachments_create_instanceTool(cfg),
		tools_builds.CreateBuilds_appencryptiondeclaration_update_to_one_relationshipTool(cfg),
		tools_builds.CreateBuilds_appencryptiondeclaration_get_to_one_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_apps_get_to_many_relatedTool(cfg),
		tools_territories.CreateTerritories_get_collectionTool(cfg),
		tools_appscreenshots.CreateAppscreenshots_delete_instanceTool(cfg),
		tools_appscreenshots.CreateAppscreenshots_get_instanceTool(cfg),
		tools_appscreenshots.CreateAppscreenshots_update_instanceTool(cfg),
		tools_profiles.CreateProfiles_certificates_get_to_many_relatedTool(cfg),
		tools_apps.CreateApps_get_instanceTool(cfg),
		tools_apps.CreateApps_update_instanceTool(cfg),
		tools_profiles.CreateProfiles_get_collectionTool(cfg),
		tools_profiles.CreateProfiles_create_instanceTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_build_get_to_one_relatedTool(cfg),
		tools_appstoreversionphasedreleases.CreateAppstoreversionphasedreleases_delete_instanceTool(cfg),
		tools_appstoreversionphasedreleases.CreateAppstoreversionphasedreleases_update_instanceTool(cfg),
		tools_betabuildlocalizations.CreateBetabuildlocalizations_build_get_to_one_relatedTool(cfg),
		tools_betatesters.CreateBetatesters_delete_instanceTool(cfg),
		tools_betatesters.CreateBetatesters_get_instanceTool(cfg),
		tools_idfadeclarations.CreateIdfadeclarations_create_instanceTool(cfg),
		tools_builds.CreateBuilds_individualtesters_get_to_many_relationshipTool(cfg),
		tools_builds.CreateBuilds_individualtesters_create_to_many_relationshipTool(cfg),
		tools_builds.CreateBuilds_individualtesters_delete_to_many_relationshipTool(cfg),
		tools_betatesters.CreateBetatesters_builds_get_to_many_relatedTool(cfg),
		tools_enduserlicenseagreements.CreateEnduserlicenseagreements_create_instanceTool(cfg),
		tools_certificates.CreateCertificates_delete_instanceTool(cfg),
		tools_certificates.CreateCertificates_get_instanceTool(cfg),
		tools_appstoreversionlocalizations.CreateAppstoreversionlocalizations_apppreviewsets_get_to_many_relatedTool(cfg),
		tools_builds.CreateBuilds_buildbetadetail_get_to_one_relatedTool(cfg),
		tools_betaappreviewdetails.CreateBetaappreviewdetails_get_instanceTool(cfg),
		tools_betaappreviewdetails.CreateBetaappreviewdetails_update_instanceTool(cfg),
		tools_apppreorders.CreateApppreorders_create_instanceTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_appstoreversionlocalizations_get_to_many_relatedTool(cfg),
		tools_apps.CreateApps_betaapplocalizations_get_to_many_relatedTool(cfg),
		tools_apps.CreateApps_betaappreviewdetail_get_to_one_relatedTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_delete_instanceTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_get_instanceTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_update_instanceTool(cfg),
		tools_appinfos.CreateAppinfos_primarysubcategoryone_get_to_one_relatedTool(cfg),
		tools_appcategories.CreateAppcategories_get_instanceTool(cfg),
		tools_apppricetiers.CreateApppricetiers_get_instanceTool(cfg),
		tools_appinfos.CreateAppinfos_appinfolocalizations_get_to_many_relatedTool(cfg),
		tools_idfadeclarations.CreateIdfadeclarations_delete_instanceTool(cfg),
		tools_idfadeclarations.CreateIdfadeclarations_update_instanceTool(cfg),
		tools_appinfos.CreateAppinfos_get_instanceTool(cfg),
		tools_appinfos.CreateAppinfos_update_instanceTool(cfg),
		tools_appcategories.CreateAppcategories_get_collectionTool(cfg),
		tools_appstoreversions.CreateAppstoreversions_idfadeclaration_get_to_one_relatedTool(cfg),
		tools_appencryptiondeclarations.CreateAppencryptiondeclarations_get_instanceTool(cfg),
		tools_betatesters.CreateBetatesters_create_instanceTool(cfg),
		tools_betatesters.CreateBetatesters_get_collectionTool(cfg),
		tools_routingappcoverages.CreateRoutingappcoverages_create_instanceTool(cfg),
		tools_appstorereviewdetails.CreateAppstorereviewdetails_create_instanceTool(cfg),
		tools_betatesters.CreateBetatesters_betagroups_get_to_many_relatedTool(cfg),
		tools_betagroups.CreateBetagroups_betatesters_get_to_many_relatedTool(cfg),
		tools_appinfos.CreateAppinfos_secondarycategory_get_to_one_relatedTool(cfg),
		tools_appinfos.CreateAppinfos_secondarysubcategorytwo_get_to_one_relatedTool(cfg),
		tools_apppreorders.CreateApppreorders_delete_instanceTool(cfg),
		tools_apppreorders.CreateApppreorders_get_instanceTool(cfg),
		tools_apppreorders.CreateApppreorders_update_instanceTool(cfg),
		tools_apps.CreateApps_inapppurchases_get_to_many_relatedTool(cfg),
		tools_betalicenseagreements.CreateBetalicenseagreements_get_instanceTool(cfg),
		tools_betalicenseagreements.CreateBetalicenseagreements_update_instanceTool(cfg),
		tools_betalicenseagreements.CreateBetalicenseagreements_app_get_to_one_relatedTool(cfg),
		tools_bundleids.CreateBundleids_app_get_to_one_relatedTool(cfg),
		tools_builds.CreateBuilds_individualtesters_get_to_many_relatedTool(cfg),
	}
}
